fix: 123

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -2,16 +2,13 @@ defaults:
   run:
     working-directory: "terraform"
 
-name: CI/CD Pipeline
+name: Spring Boot CI/CD Pipeline
 
 on:
   push:
     branches:
       - main
   pull_request:
-    branches:
-      - main
-  workflow_dispatch:
 
 jobs:
   build-and-deploy:
@@ -28,105 +25,107 @@ jobs:
         with:
           credentials_json: ${{ secrets.GCP_SA }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
-
-      - name: Terraform Init
-        id: init
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
-
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GH_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-            <details><summary>Show Plan</summary>
-
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-
-            </details>
-
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: "17"
-
       - name: Set Environment Variables
         run: |
-          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+          if [refs/heads/main"]; then
             echo "DEPLOY_MODE=full" >> $GITHUB_ENV
           else
             echo "DEPLOY_MODE=deploy-only" >> $GITHUB_ENV
           fi
 
-      - name: Build JAR (Only for Main Branch)
-        run: |
-          if [[ "$DEPLOY_MODE" == "full" ]]; then
-            mvn clean package -DskipTests
-          else
-            echo "Skipping JAR build"
-          fi
+      - name: Echo Set Environment Variables
+        run: echo $GITHUB_ENV
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2
 
-      - name: Build & Push Docker Image (Only for Main Branch)
-        run: |
-          if [[ "$DEPLOY_MODE" == "full" ]]; then
-            gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
-            docker build -t northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest .
-            docker push northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest
-          else
-            echo "Skipping Docker image build and push"
-          fi
+      # - name: Terraform Format
+      #   id: fmt
+      #   run: terraform fmt -check
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: |
-          if [[ "$DEPLOY_MODE" == "full" ]]; then
-            terraform apply -auto-approve -input=false
-          else
-            echo "Skipping Terraform Apply"
-          fi
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
 
-      - name: Terraform Apply (For pushing non-main)
-        run: |
-          if [[ "$DEPLOY_MODE" == "deploy-only" ]]; then
-            terraform apply -auto-approve -var="image_tag=latest"
-          else
-            echo "Skipping Terraform Apply"
-          fi
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
+
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
+
+      # - uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GH_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
+      #       <details><summary>Show Plan</summary>
+
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
+
+      #       </details>
+
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Set up JDK 17
+      #   uses: actions/setup-java@v3
+      #   with:
+      #     distribution: "temurin"
+      #     java-version: "17"
+
+      # - name: Build JAR (Only for Main Branch)
+      #   run: |
+      #     if [[ "$DEPLOY_MODE" == "full" ]]; then
+      #       mvn clean package -DskipTests
+      #     else
+      #       echo "Skipping JAR build"
+      #     fi
+
+      # - name: Build & Push Docker Image (Only for Main Branch)
+      #   run: |
+      #     if [[ "$DEPLOY_MODE" == "full" ]]; then
+      #       gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
+      #       docker build -t northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest .
+      #       docker push northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest
+      #     else
+      #       echo "Skipping Docker image build and push"
+      #     fi
+
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: |
+      #     if [[ "$DEPLOY_MODE" == "full" ]]; then
+      #       terraform apply -auto-approve -input=false
+      #     else
+      #       echo "Skipping Terraform Apply"
+      #     fi
+
+      # - name: Terraform Apply (For pushing non-main)
+      #   run: |
+      #     if [[ "$DEPLOY_MODE" == "deploy-only" ]]; then
+      #       terraform apply -auto-approve -var="image_tag=latest"
+      #     else
+      #       echo "Skipping Terraform Apply"
+      #     fi
